### ISSUE TITLE
Bug: /v1/health/service endpoint is broken

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/api.opensauced.pizza#52]
### Describe the bug

The endpoint `https://api.opensauced.pizza/v1/health/service` is broken. It returns an error page.

![image](https://user-images.githubusercontent.com/52013393/195419058-e64d2fa2-36f3-43e6-b06d-64112799b409.png)

On local development, it gives a 500 internal error, and in console, this error:

```[Nest] 28396  - 10/12/2022, 8:20:00 PM   ERROR [ExceptionsHandler] The following path is invalid (should be X:\...): /
InvalidPathError: The following path is invalid (should be X:\...): /
    at powershellCmd (I:\CODING\MLH\api.opensauced.pizza\node_modules\check-disk-space\dist\check-disk-space.cjs:144:24)
    at new Promise (<anonymous>)
    at checkWin32 (I:\CODING\MLH\api.opensauced.pizza\node_modules\check-disk-space\dist\check-disk-space.cjs:143:20)
    at DiskHealthIndicator.checkDiskSpace (I:\CODING\MLH\api.opensauced.pizza\node_modules\check-disk-space\dist\check-disk-space.cjs:194:16)
    at DiskHealthIndicator.<anonymous> (I:\CODING\MLH\api.opensauced.pizza\node_modules\@nestjs\terminus\dist\health-indicator\disk\disk.health.js:82:47)
    at Generator.next (<anonymous>)
    at I:\CODING\MLH\api.opensauced.pizza\node_modules\@nestjs\terminus\dist\health-indicator\disk\disk.health.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (I:\CODING\MLH\api.opensauced.pizza\node_modules\@nestjs\terminus\dist\health-indicator\disk\disk.health.js:16:12)       
    at DiskHealthIndicator.checkStorage (I:\CODING\MLH\api.opensauced.pizza\node_modules\@nestjs\terminus\dist\health-indicator\disk\disk.health.js:81:16)```

### Steps to reproduce

Go to https://api.opensauced.pizza/v1/health/service

### Affected services

api.opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Production, Development

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Deadreyo** [comment]
So the error seems to originate from `health.controller.ts` file, in lines 39 and 43. I guess those paths should be something like `C://...` since in `check-disk-space.cjs` it returns an error when this condition is not true `if (directoryPath.charAt(1) !== ':')`

**Comment by Deadreyo** [comment]
I have not taken this issue so anyone can feel free to pick it up

**Comment by 0-vortex** [comment]
That is actually incorrect. 

The page you are seeing occurs because the containers are currently deployed via the Digital Ocean Application specification, and HTTP `5xx` errors lead to a default HTML page. Locally, the API correctly returns the 503 result, failing the disk check space with a threshold of 70% out of 100GB.

If the nest instance is unable to read the disk space and returns a 500 server error, you can debug the error to gain insight, however it's not fixable due to the fact that our deployment platform for this is linux - as such, the terminus disk checks would always look for a linux fs root path, and even if that npm package would be cross platform it would likely fail as it is designed to only work on linux intentionally.

One pro tip I can give you is building the docker container and then testing if it works by injecting the existing env:

```
docker build . --tag test
docker run -p 8001:3001 -v "api":"/usr/src/app/" --env-file .env -dit test
```

What that does is it creates a docker image from the existing folder and tags it `test` (running the command twice doesn't overwrite this necessarily), then the next one attaches container port 3001 to your `localhost:8001` so you can run container on 8001 and local development on 3001, injects the env file you have locally into that container and creates a docker volume you can inspect named `api`.

That's about as far as you can go with this, the health controller being a front facing critical endpoint, hacking it to make local development work is not feasible. The docker container however replicates the production environment, and as such, can be used for testing. I am 99% convinced the disk checker package is not fixable on windows, so maybe we could rewire this into extending the local development quirks, or researching a stable way for windows users to run this, exploring ideas like WSL or VSC devcontainers, linux web IDEs or pure local development. 

I would opt for just saying "don't expect that endpoint to work on windows because {insert your existing knowledge and experience here}" 🍕
